### ISSUE TITLE
[Android] Nested ViewPagers with same orientation are not scrollable

### ISSUE THREAD

**Issue by brsaylor2** [callstack/react-native-pager-view#303]
## Environment

- React Native 0.63.4
- Android 10
- ViewPager 5.0.12

## Description

In versions 3 and 4 of this library, it is possible to have one ViewPager inside another, with the same orientation, and either one can be scrolled depending on where the user swipes the screen.

In version 5, the inner ViewPager is not scrollable: swiping it scrolls the outer one.

This issue doesn't occur if the inner and outer ViewPagers have different orientations.

## Reproducible Demo

Here is a fork demonstrating the bug in the example app (it's the "Nested ViewPagers Example" at the bottom):
https://github.com/brsaylor2/react-native-viewpager/tree/nested-demo

Here's the actual demo code, based on BasicViewPagerExample.tsx: https://github.com/brsaylor2/react-native-viewpager/blob/nested-demo/example/src/NestedViewPagersExample.tsx

Here's a version showing that the same thing works in v4:
https://github.com/brsaylor2/react-native-viewpager/tree/nested-demo-v4

**Comment by KingAmo** [comment]
same here... any workaround ?

**Comment by huuthan** [comment]
I have the same problem. Is there any solution to fix it?

- React Native 0.64
- Android 10
- ViewPager 5.1.3

**Comment by ifsnow** [comment]
@troZee Do you have any plans for this issue? This is the biggest reason for not using the new version. :-(

**Comment by badaz** [comment]
Hello, I got this bug too, using react-native-tab-view along with react-native-page-view 5.4.0, here is a snack repro link https://snack.expo.dev/Q6wjaGD99 I provided in a misplaced  issue here : https://github.com/satya164/react-native-tab-view/issues/1233 . This does not happen in v4

**Comment by NiuGuohui** [comment]
Is there any solution?

**Comment by NiuGuohui** [comment]
I tried to fix this issue: #423

**Comment by brsaylor2** [comment]
This issue is fixed for me in the current version. Thanks, @NiuGuohui!

**Comment by grahammendick** [comment]
`ViewPager2` doesn't support nested scrolling with same orientation but `ViewPager` does. That's why react-native-pager-view lost support in version 4.

The only reason that I can see to switch to ViewPager2 is to bring RTL (right-to-left) support. So, in the Navigation router I continue to [use ViewPager for LTR and only use ViewPager2 for RTL](https://github.com/grahammendick/navigation/blob/e0796c6c589833638b1548379ffa08c91534debd/NavigationReactNative/src/TabBar.tsx#L58). @NiuGuohui I thought you might be interested in seeing an alternative approach.
