### ISSUE TITLE
Drop support for curl 

### ISSUE THREAD

**Issue by troZee** [callstack/react-native-pager-view#343]
Hello everyone, 
I would like to drop support for the curl transition type. I was struggling with fixing some issues on iOS and this component does not give you the ability to control the behavior. The second thing is that this feature is not supported on Android. It is hard to maintain the feature, which is impossible to fix without straightforward solutions and with a lack of support for an Android. 

More context here: 
https://github.com/callstack/react-native-pager-view/issues/236

Alternatives: 
- https://github.com/darenju/react-flip-page
- own custom implementation, which uses reanimated and gesture handler
- fork pager-view and add this library to the project https://github.com/iamarbaazkhan/Simple-Page-Curl-Effect-Android

**Comment by alpha0010** [comment]
I have not been using curl transition (due to lack of Android support), so I cannot comment on how well it works/does not work.  However I do like the animation, and aimed to use it if I ever get around to the Android side.

- https://github.com/harism/android-pagecurl is another library (with, perhaps, more detailed animation)
