### ISSUE TITLE
[Android] getReactContext does not work in < 63

### ISSUE THREAD

**Issue by biancamagalhaes** [callstack/react-native-pager-view#394]
## Environment

"react": "16.9.0",
"react-native": "0.61.5",
"react-native-pager-view": "^5.2.1",

## Description

The error was the following one:

<img width="1025" alt="Captura de Tela 2021-07-20 às 18 34 11" src="https://user-images.githubusercontent.com/37228344/126398431-9d55f983-30c9-41b7-ab41-6da3bf52c18f.png">

I'm afraid of this recent version of react-native-pager-view only works with react-native 0.63+ because of the getReactContext() function.

## Reproducible Demo

To reproduce it is just run an android build, even in debug it shouldn't works. 
OBS: you need to use the environment above.

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/blob/master/android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt#L85

Above line is affected due to fact, UIManagerHelper does not exist in the rn 0.61

https://github.com/facebook/react-native/blob/v0.61.5/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerHelper.java

**Comment by troZee** [comment]
@biancamagalhaes as temporary workaround, you can just copy/paste that method https://github.com/facebook/react-native/blob/v0.64.2/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerHelper.java#L138 and replace it with this one https://github.com/callstack/react-native-pager-view/blob/master/android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt#L85

**Comment by biancamagalhaes** [comment]
Tks :), everything works fine now!
