### ISSUE TITLE
Please upgrade kotlin version

### ISSUE THREAD

**Issue by AnhDTN** [callstack/react-native-pager-view#617]
Hello,

I got error The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-pager-view' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.30,
so, if you have time, can you upgrade kotlin version?

Thank.

**Comment by radko93** [comment]
You override kotlin version while setting it in your project   def kotlin_version = rootProject.ext.has('kotlinVersion') ? rootProject.ext.get('kotlinVersion') : project.properties['PagerView_kotlinVersion']

**Comment by nijarv** [comment]
@AnhDTN were you able to fix the issue?

**Comment by Abhishektaurus** [comment]
I am still facing the same issue..can any one please help here ?

**Comment by lfrallon** [comment]
> You override kotlin version while setting it in your project
> 
> https://github.com/callstack/react-native-pager-view/blob/e01cd62017d5fb1de262f744ffd9d21b63179899/android/build.gradle#L3

See if you have defined your kotlin version with something like `kotlin_version = '<version>'` in your build.gradle. Then you need to change it into `kotlinVersion` since that is what react-native-pager-view defined in their script. And also check your android/app/build.gradle too.

It works for me.
